### ISSUE TITLE
Fix empty observation bug

### ISSUE THREAD

**Issue by Bobsters6666** [UoaWDCC/patrols#83]
## Description

As a patroller
I want to create observations without bugs,
So that I can carry out my report smoothly 

## Proposed Solution
- Find the bug in the reportObservations components 
- Potentially look to rehaul the current observation addition and deletion logic. 

## Acceptance Criteria

- Create observations without duplicates.
- Other features in report continue to work normally. 

## Notes

```[tasklist]
### Tasks
- [ ] https://github.com/UoaWDCC/patrols/issues/86
```

**Comment by raymondyangdev** [comment]
Closed in #89
