### ISSUE TITLE
Add subcategories for each observation  

### ISSUE THREAD

**Issue by Bobsters6666** [UoaWDCC/patrols#86]
## Description

As a Patroller
I want to select the subcategory alongside the main category for each observation.
So that CPNZ and Police can better categorise the type of incident. 

## Proposed Solution

- Each observation should also contain a subcategory field (modify new observation popup form)
- When adding an observation, after the patroller selects the ‘main’ category, the sub category select box should be populated accordingly. 
- Need to modify the DB to include the sub categories
- When patroller logs off, calculate the total number of hours travelled on this shift (shift duration * number of registered patrollers). 

## Acceptance Criteria

- Patroller can select category and subcategory for each observation, and data gets sent correctly to backend. 
- Total number of hours travelled is accurately calculated and stored in DB under statistics. 

## Notes
[#83](https://github.com/UoaWDCC/patrols/issues/83)
```[tasklist]
### Tasks
- [ ] https://github.com/UoaWDCC/patrols/issues/83
```

**Comment by raymondyangdev** [comment]
@Bobsters6666 
What are the subcategories they want us to include?

**Comment by Bobsters6666** [comment]
I forwarded the email to you and Joshua that includes on the sub categories Scott wants us to include.

I'll forward them again
@raymondyangdev @JoshuaMak2003

**Comment by JoshuaMak2003** [comment]
calculate the total number of hours travelled on this shift --> I'll assume the start is when the email is when the app fetches the code from the email and they really really start the shift?

**Comment by Bobsters6666** [comment]
Nonono - the total number of hours is just the start time to the end time. If 18:00 - 20:00 then its 2 hours.

**Comment by JoshuaMak2003** [comment]
Sorry, I should've asked this earlier. I am a little confused about which table of stats I should store as I am not sure what the meaning of each table is.

There are:
district_stats_dev
district_stats_prod
stats_dev
stats_prod

Also, if registered, does it mean that if the guest patroller is not registered, we do not include them in the calculating hours?

Another question would be, as the guestPatrollers aren't being stored at the moment, Should the non-registered ones be registered on the DB if the user ticks the not registered box on the logon form?

**Comment by Bobsters6666** [comment]
The way we're modifying right now will be stats_dev. The district_stats is the old CPNZ method. 

If you have a look at Seth + Joey's task, they're adding a new field in the logon form that let's the patroller select the number of registered patroller's on this shift. I think we can edit the current shift table to include this field - so we can use this number + the start end times to calculate the hours. 

Don't worry about storing guest patrollers.

**Comment by JoshuaMak2003** [comment]
Oh noo... I spent half the day trying to figure out how I can count and add
the amount of guest patrollers and stuff, from the logon form ... Welp....

Ok I'll just add a new role to count the amount of hours... For now I will
assume there will always be at least 2 registered patrollers.
